#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-haml
Version  : 4.0.7
Release  : 8
URL      : https://rubygems.org/downloads/haml-4.0.7.gem
Source0  : https://rubygems.org/downloads/haml-4.0.7.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT WTFPL
Requires: rubygem-haml-bin
BuildRequires : ruby
BuildRequires : rubygem-actionpack
BuildRequires : rubygem-minitest
BuildRequires : rubygem-nokogiri
BuildRequires : rubygem-rails
BuildRequires : rubygem-railties
BuildRequires : rubygem-rbench
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-tilt

%description
# Haml
[![Build Status](https://secure.travis-ci.org/haml/haml.png?branch=master)](http://travis-ci.org/haml/haml)

%package bin
Summary: bin components for the rubygem-haml package.
Group: Binaries

%description bin
bin components for the rubygem-haml package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n haml-4.0.7
gem spec %{SOURCE0} -l --ruby > rubygem-haml.gemspec

%build
gem build rubygem-haml.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
haml-4.0.7.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/haml-4.0.7.gem
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/.yardopts
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/CHANGELOG.md
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/FAQ.md
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/MIT-LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/README.md
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/REFERENCE.md
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/bin/haml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml.rb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/buffer.rb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/compiler.rb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/engine.rb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/error.rb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/exec.rb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/filters.rb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/helpers/action_view_extensions.rb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/helpers/action_view_mods.rb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/helpers/action_view_xss_mods.rb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/helpers/safe_erubis_template.rb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/helpers/xss_mods.rb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/options.rb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/parser.rb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/railtie.rb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/sass_rails_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/template.rb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/template/options.rb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/template/plugin.rb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/util.rb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/engine_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/erb/_av_partial_1.erb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/erb/_av_partial_2.erb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/erb/action_view.erb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/erb/standard.erb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/filters_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/gemfiles/Gemfile.rails-3.0.x
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/gemfiles/Gemfile.rails-3.1.x
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/gemfiles/Gemfile.rails-3.2.x
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/gemfiles/Gemfile.rails-4.0.x
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/haml-spec/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/haml-spec/README.md
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/haml-spec/lua_haml_spec.lua
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/haml-spec/perl_haml_test.pl
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/haml-spec/ruby_haml_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/haml-spec/tests.json
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/helper_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/markaby/standard.mab
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/mocks/article.rb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/parser_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/results/content_for_layout.xhtml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/results/eval_suppressed.xhtml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/results/helpers.xhtml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/results/helpful.xhtml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/results/just_stuff.xhtml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/results/list.xhtml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/results/nuke_inner_whitespace.xhtml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/results/nuke_outer_whitespace.xhtml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/results/original_engine.xhtml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/results/partial_layout.xhtml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/results/partial_layout_erb.xhtml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/results/partials.xhtml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/results/render_layout.xhtml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/results/silent_script.xhtml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/results/standard.xhtml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/results/tag_parsing.xhtml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/results/very_basic.xhtml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/results/whitespace_handling.xhtml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/template_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/templates/_av_partial_1.haml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/templates/_av_partial_1_ugly.haml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/templates/_av_partial_2.haml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/templates/_av_partial_2_ugly.haml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/templates/_layout.erb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/templates/_layout_for_partial.haml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/templates/_partial.haml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/templates/_text_area.haml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/templates/_text_area_helper.html.haml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/templates/action_view.haml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/templates/action_view_ugly.haml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/templates/breakage.haml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/templates/content_for_layout.haml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/templates/eval_suppressed.haml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/templates/helpers.haml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/templates/helpful.haml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/templates/just_stuff.haml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/templates/list.haml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/templates/nuke_inner_whitespace.haml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/templates/nuke_outer_whitespace.haml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/templates/original_engine.haml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/templates/partial_layout.haml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/templates/partial_layout_erb.erb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/templates/partialize.haml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/templates/partials.haml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/templates/render_layout.haml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/templates/silent_script.haml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/templates/standard.haml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/templates/standard_ugly.haml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/templates/tag_parsing.haml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/templates/very_basic.haml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/templates/whitespace_handling.haml
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/haml-4.0.7/test/util_test.rb
/usr/lib64/ruby/gems/2.3.0/specifications/haml-4.0.7.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/haml
